// `archiver` is a CommonJS module whose runtime export is a callable factory,
// but @types/archiver only declares the class shape. We import the namespace
// (for the Archiver type) and load the factory via require() with a precise
// cast so TypeScript treats it as the function it actually is at runtime.
import * as archiverNs from 'archiver';
import { Writable } from 'stream';
import { HospitalReport } from './report.types';

type ArchiverFactory = (
  format: 'zip' | 'tar',
  options?: archiverNs.ArchiverOptions,
) => archiverNs.Archiver;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const archiver = require('archiver') as ArchiverFactory;

/**
 * Streams a zip bundle with one CSV per logical entity. We write CSVs by
 * hand (no third-party CSV lib) because the dataset is small and uniform —
 * RFC 4180 quoting handles the few fields with commas / newlines / quotes.
 */

function csvEscape(value: unknown): string {
  if (value === null || value === undefined) return '';
  const s = typeof value === 'string' ? value : String(value);
  if (s.includes('"') || s.includes(',') || s.includes('\n') || s.includes('\r')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function toCsv(headers: string[], rows: Array<Record<string, unknown>>): string {
  const lines: string[] = [];
  lines.push(headers.join(','));
  for (const row of rows) {
    lines.push(headers.map((h) => csvEscape(row[h])).join(','));
  }
  return lines.join('\n');
}

export function renderHospitalReportZip(report: HospitalReport, output: Writable): Promise<void> {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('warning', (err: any) => {
      if (err && err.code !== 'ENOENT') reject(err);
    });
    archive.on('error', reject);
    output.on('finish', () => resolve());
    output.on('close', () => resolve());
    output.on('error', reject);

    archive.pipe(output);

    archive.append(buildSummaryCsv(report), { name: 'summary.csv' });
    archive.append(buildPatientsCsv(report), { name: 'patients.csv' });
    archive.append(buildEncountersCsv(report), { name: 'encounters.csv' });
    archive.append(buildDoctorsCsv(report), { name: 'doctors.csv' });
    archive.append(buildDoctorTrendsCsv(report), { name: 'doctor_trends.csv' });
    archive.append(buildAppointmentsCsv(report), { name: 'appointments.csv' });
    archive.append(buildIpdCsv(report), { name: 'ipd.csv' });
    archive.append(buildPharmacyCsv(report), { name: 'pharmacy.csv' });
    archive.append(buildLabCsv(report), { name: 'lab.csv' });
    archive.append(buildBillingCsv(report), { name: 'billing.csv' });
    archive.append(buildStaffCollectionsCsv(report), { name: 'staff_collections.csv' });
    archive.append(buildAbdmCsv(report), { name: 'abdm.csv' });

    archive.finalize().catch(reject);
  });
}

function buildSummaryCsv(r: HospitalReport): string {
  const h = r.header.hospital;
  const rows: Array<Record<string, unknown>> = [
    { Field: 'Hospital', Value: h?.name || '—' },
    { Field: 'Hospital code', Value: h?.code || '—' },
    { Field: 'Type', Value: h?.type || '—' },
    { Field: 'Address', Value: h ? `${h.address}, ${h.city}, ${h.state} ${h.pincode}` : '—' },
    { Field: 'Phone', Value: h?.phone || '—' },
    { Field: 'Email', Value: h?.email || '—' },
    { Field: 'HIP ID', Value: h?.hipId || '—' },
    { Field: 'HIU ID', Value: h?.hiuId || '—' },
    { Field: 'HFR Facility ID', Value: h?.hfrFacilityId || '—' },
    { Field: 'ABDM enabled', Value: h?.abdmEnabled ? 'Yes' : 'No' },
    { Field: 'Reporting window', Value: r.header.range.label },
    { Field: 'Range preset', Value: r.header.range.preset },
    { Field: 'Range from', Value: r.header.range.from ? r.header.range.from.toISOString() : '—' },
    { Field: 'Range to', Value: r.header.range.to ? r.header.range.to.toISOString() : '—' },
    { Field: 'Generated at (IST)', Value: r.header.generatedAtIst },
    { Field: 'Generated by', Value: `${r.header.generatedBy.name} (${r.header.generatedBy.role})` },
    { Field: 'Patients lifetime', Value: r.patientKpis.totalLifetime },
    { Field: 'Patients in range', Value: r.patientKpis.totalInRange },
    { Field: 'ABHA-linked lifetime', Value: r.patientKpis.abhaLinkedLifetime },
    { Field: 'ABHA % lifetime', Value: r.patientKpis.abhaPercentLifetime },
    { Field: 'ABHA-linked in range', Value: r.patientKpis.abhaLinkedInRange },
    { Field: 'ABHA % in range', Value: r.patientKpis.abhaPercentInRange },
    { Field: 'KYC verified', Value: r.patientKpis.kycVerifiedLifetime },
    { Field: 'Encounters in range', Value: r.encounters.totalInRange },
    { Field: 'Total revenue', Value: r.billing.totalRevenue },
    { Field: 'Pharmacy revenue', Value: r.pharmacy.pharmacyRevenue },
    { Field: 'IPD admissions', Value: r.ipd.admissionsInRange },
    { Field: 'Bed occupancy %', Value: r.ipd.bedOccupancyPercent },
    { Field: 'Consents requested', Value: r.abdm.consents.requested },
    { Field: 'Consents granted', Value: r.abdm.consents.granted },
  ];
  return toCsv(['Field', 'Value'], rows);
}

function buildPatientsCsv(r: HospitalReport): string {
  const headers = [
    'UHID', 'First name', 'Last name', 'Middle name', 'Gender', 'DOB', 'Age',
    'Mobile', 'Email', 'ABHA number', 'ABHA address', 'KYC status', 'ABHA linked at',
    'City', 'State', 'Registered at', 'Source', 'Visits in range', 'Last visit',
    'Lifetime spend INR',
  ];
  const rows = r.patientRoster.map((p) => ({
    'UHID': p.uhid,
    'First name': p.firstName,
    'Last name': p.lastName,
    'Middle name': p.middleName,
    'Gender': p.gender,
    'DOB': p.dob,
    'Age': p.age,
    'Mobile': p.mobile,
    'Email': p.email,
    'ABHA number': p.abhaNumber,
    'ABHA address': p.abhaAddress,
    'KYC status': p.kycStatus,
    'ABHA linked at': p.abhaLinkedAt,
    'City': p.city,
    'State': p.state,
    'Registered at': p.registeredAt,
    'Source': p.registrationSource,
    'Visits in range': p.visitsInRange,
    'Last visit': p.lastVisitAt,
    'Lifetime spend INR': p.lifetimeSpend,
  }));
  return toCsv(headers, rows);
}

function buildEncountersCsv(r: HospitalReport): string {
  const headers = ['Section', 'Bucket', 'Count'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Section: 'TOTAL', Bucket: 'Encounters in range', Count: r.encounters.totalInRange });
  rows.push({ Section: 'TOTAL', Bucket: 'Average per day', Count: r.encounters.avgPerDay });
  for (const t of r.encounters.byType) rows.push({ Section: 'BY TYPE', Bucket: t.type, Count: t.count });
  for (const s of r.encounters.byStatus) rows.push({ Section: 'BY STATUS', Bucket: s.status, Count: s.count });
  for (const d of r.encounters.dailyTrend) {
    rows.push({ Section: 'DAILY', Bucket: `${d.label} ${d.date.substring(0, 10)}`, Count: d.count });
  }
  return toCsv(headers, rows);
}

function buildDoctorsCsv(r: HospitalReport): string {
  const headers = [
    'Doctor', 'Specialization', 'Department', 'HPR ID', 'Reg. no.', 'Active',
    'Unique patients', 'Encounters', 'OPD', 'IPD', 'Emergency', 'Tele.', 'Follow-ups',
    'Days worked', 'Avg/day', 'Cancelled', 'No-show', 'Revenue INR',
  ];
  const rows = r.doctors.map((d) => ({
    'Doctor': d.name,
    'Specialization': d.specialization,
    'Department': d.department,
    'HPR ID': d.hprId,
    'Reg. no.': d.registrationNo,
    'Active': d.isActive ? 'Yes' : 'No',
    'Unique patients': d.uniquePatients,
    'Encounters': d.encounters,
    'OPD': d.opd,
    'IPD': d.ipd,
    'Emergency': d.emergency,
    'Tele.': d.teleconsult,
    'Follow-ups': d.followUps,
    'Days worked': d.daysWorked,
    'Avg/day': d.avgPatientsPerDay,
    'Cancelled': d.appointmentsCancelled,
    'No-show': d.appointmentsNoShow,
    'Revenue INR': d.revenueAttributed,
  }));
  return toCsv(headers, rows);
}

function buildDoctorTrendsCsv(r: HospitalReport): string {
  const headers = ['Doctor', 'Cadence', 'Bucket', 'Patients'];
  const rows: Array<Record<string, unknown>> = [];
  for (const d of r.doctors) {
    for (const x of d.trends.daily) rows.push({ Doctor: d.name, Cadence: 'Daily', Bucket: `${x.label} ${x.date.substring(0, 10)}`, Patients: x.count });
    for (const x of d.trends.weekly) rows.push({ Doctor: d.name, Cadence: 'Weekly', Bucket: `Week of ${x.weekStart}`, Patients: x.count });
    for (const x of d.trends.monthly) rows.push({ Doctor: d.name, Cadence: 'Monthly', Bucket: x.month, Patients: x.count });
    for (const x of d.trends.yearly) rows.push({ Doctor: d.name, Cadence: 'Yearly', Bucket: x.year, Patients: x.count });
  }
  return toCsv(headers, rows);
}

function buildAppointmentsCsv(r: HospitalReport): string {
  const headers = ['Doctor', 'Total', 'Completed', 'Cancelled', 'No-show'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({
    Doctor: 'TOTAL',
    Total: r.appointments.total,
    Completed: r.appointments.completed,
    Cancelled: r.appointments.cancelled,
    'No-show': r.appointments.noShow,
  });
  for (const d of r.appointments.byDoctor) {
    rows.push({
      Doctor: d.name,
      Total: d.total,
      Completed: d.completed,
      Cancelled: d.cancelled,
      'No-show': d.noShow,
    });
  }
  return toCsv(headers, rows);
}

function buildIpdCsv(r: HospitalReport): string {
  const headers = ['Section', 'Ward / metric', 'Type', 'Admissions', 'Revenue INR'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Admissions in range', Admissions: r.ipd.admissionsInRange });
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Currently admitted', Admissions: r.ipd.currentlyAdmitted });
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Discharges', Admissions: r.ipd.discharges });
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Avg length of stay (days)', Admissions: r.ipd.avgLengthOfStay });
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Bed occupancy %', Admissions: r.ipd.bedOccupancyPercent });
  rows.push({ Section: 'TOTAL', 'Ward / metric': 'Total IPD revenue', 'Revenue INR': r.ipd.totalIpdRevenue });
  for (const w of r.ipd.byWard) {
    rows.push({
      Section: 'BY WARD',
      'Ward / metric': w.ward,
      Type: w.type,
      Admissions: w.admissions,
      'Revenue INR': w.revenue,
    });
  }
  return toCsv(headers, rows);
}

function buildPharmacyCsv(r: HospitalReport): string {
  const headers = ['Section', 'Item / metric', 'Qty', 'Revenue INR'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Section: 'TOTAL', 'Item / metric': 'Dispensed quantity', Qty: r.pharmacy.dispensedQty });
  rows.push({ Section: 'TOTAL', 'Item / metric': 'Pharmacy revenue', 'Revenue INR': r.pharmacy.pharmacyRevenue });
  rows.push({ Section: 'TOTAL', 'Item / metric': 'Current stock value', 'Revenue INR': r.pharmacy.currentStockValue });
  rows.push({ Section: 'TOTAL', 'Item / metric': 'Items below reorder level', Qty: r.pharmacy.lowStockCount });
  rows.push({ Section: 'TOTAL', 'Item / metric': 'Batches expiring within 90d', Qty: r.pharmacy.expiringSoonCount });
  for (const m of r.pharmacy.topByQty) {
    rows.push({ Section: 'TOP BY QTY', 'Item / metric': m.name, Qty: m.qty, 'Revenue INR': m.revenue });
  }
  for (const m of r.pharmacy.topByRevenue) {
    rows.push({ Section: 'TOP BY REVENUE', 'Item / metric': m.name, Qty: m.qty, 'Revenue INR': m.revenue });
  }
  return toCsv(headers, rows);
}

function buildLabCsv(r: HospitalReport): string {
  const headers = ['Section', 'Bucket', 'Count'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Section: 'TOTAL', Bucket: 'Tests ordered', Count: r.lab.ordered });
  rows.push({ Section: 'TOTAL', Bucket: 'Completed', Count: r.lab.completed });
  rows.push({ Section: 'TOTAL', Bucket: 'Pending', Count: r.lab.pending });
  rows.push({ Section: 'TOTAL', Bucket: 'Avg TAT (hrs)', Count: r.lab.avgTatHours });
  for (const c of r.lab.byCategory) {
    rows.push({ Section: 'BY CATEGORY', Bucket: c.category, Count: c.count });
  }
  return toCsv(headers, rows);
}

function buildBillingCsv(r: HospitalReport): string {
  const headers = ['Section', 'Bucket', 'Count', 'Amount INR'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Section: 'TOTAL', Bucket: 'Total revenue (paid)', 'Amount INR': r.billing.totalRevenue });
  rows.push({ Section: 'TOTAL', Bucket: 'Discounts given', 'Amount INR': r.billing.discountsGiven });
  rows.push({ Section: 'TOTAL', Bucket: 'Outstanding pending', 'Amount INR': r.billing.outstanding.pending });
  rows.push({ Section: 'TOTAL', Bucket: 'Outstanding partial', 'Amount INR': r.billing.outstanding.partial });
  rows.push({ Section: 'BY SOURCE', Bucket: 'Consultation', 'Amount INR': r.billing.bySource.consultation });
  rows.push({ Section: 'BY SOURCE', Bucket: 'Pharmacy', 'Amount INR': r.billing.bySource.pharmacy });
  rows.push({ Section: 'BY SOURCE', Bucket: 'Labs', 'Amount INR': r.billing.bySource.labs });
  rows.push({ Section: 'BY SOURCE', Bucket: 'Scans', 'Amount INR': r.billing.bySource.scans });
  rows.push({ Section: 'BY SOURCE', Bucket: 'IPD', 'Amount INR': r.billing.bySource.ipd });
  for (const m of r.billing.byMethod) {
    rows.push({ Section: 'BY METHOD', Bucket: m.method, Count: m.count, 'Amount INR': m.amount });
  }
  for (const d of r.billing.dailyTrend) {
    rows.push({
      Section: 'DAILY',
      Bucket: `${d.label} ${d.date.substring(0, 10)}`,
      'Amount INR': d.revenue,
    });
  }
  return toCsv(headers, rows);
}

function buildStaffCollectionsCsv(r: HospitalReport): string {
  // Wide layout (one row per collector, methods as columns) is friendlier
  // for spreadsheet pivots than long format. Methods we don't recognise
  // collapse into "Other" so the row total still reconciles.
  const headers = [
    'Collector', 'Role', 'Email', 'Receipts', 'Total INR',
    'Cash', 'UPI', 'Card', 'Bank', 'Other',
    'First collected', 'Last collected',
  ];
  const m = (s: typeof r.billing.byStaff[number], key: string) =>
    s.byMethod.find((b) => b.method === key)?.amount || 0;
  const rows = r.billing.byStaff.map((s) => ({
    Collector: s.name,
    Role: s.role || '',
    Email: s.email || '',
    Receipts: s.paymentCount,
    'Total INR': s.total,
    Cash: m(s, 'CASH'),
    UPI: m(s, 'UPI'),
    Card: m(s, 'CARD'),
    Bank: m(s, 'BANK_TRANSFER'),
    Other: s.byMethod
      .filter((x) => !['CASH', 'UPI', 'CARD', 'BANK_TRANSFER'].includes(x.method))
      .reduce((acc, x) => acc + x.amount, 0),
    'First collected': s.firstCollectedAt || '',
    'Last collected': s.lastCollectedAt || '',
  }));
  return toCsv(headers, rows);
}

function buildAbdmCsv(r: HospitalReport): string {
  const headers = ['Metric', 'Count'];
  const rows: Array<Record<string, unknown>> = [];
  rows.push({ Metric: 'Consents requested', Count: r.abdm.consents.requested });
  rows.push({ Metric: 'Consents granted', Count: r.abdm.consents.granted });
  rows.push({ Metric: 'Consents denied', Count: r.abdm.consents.denied });
  rows.push({ Metric: 'Consents revoked', Count: r.abdm.consents.revoked });
  rows.push({ Metric: 'Consents expired', Count: r.abdm.consents.expired });
  rows.push({ Metric: 'Consents purged', Count: r.abdm.consents.purged });
  rows.push({ Metric: 'Care contexts linked', Count: r.abdm.careContextsLinked });
  rows.push({ Metric: 'Scan & Share check-ins', Count: r.abdm.scanShareCheckIns });
  rows.push({ Metric: 'HIU records received', Count: r.abdm.externalRecordsReceived });
  return toCsv(headers, rows);
}
