import ExcelJS from 'exceljs';
import { Writable } from 'stream';
import { HospitalReport } from './report.types';

/**
 * Multi-sheet Excel workbook for the hospital report. The structure mirrors
 * the PDF: every section gets its own sheet so analysts can pivot/sort the
 * raw rows. Streamed via ExcelJS's `xlsx.write(stream)` so we don't have to
 * materialise the entire workbook in memory.
 *
 * Convention: numeric columns get number formats applied at the column
 * level (rather than per-cell) so Excel interprets them as numbers and the
 * sums on a column actually work for the user.
 */

const HEADER_FILL: ExcelJS.FillPattern = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF0F766E' },
};

const HEADER_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  color: { argb: 'FFFFFFFF' },
  size: 11,
};

const ZEBRA_FILL: ExcelJS.FillPattern = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFF8FAFC' },
};

interface ColSpec {
  header: string;
  key: string;
  width?: number;
  numFmt?: string;
}

function applyHeaderStyle(sheet: ExcelJS.Worksheet) {
  const row = sheet.getRow(1);
  row.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT as ExcelJS.Font;
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
    cell.border = {
      bottom: { style: 'thin', color: { argb: 'FF0F766E' } },
    };
  });
  row.height = 22;
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
}

function applyZebra(sheet: ExcelJS.Worksheet) {
  for (let i = 2; i <= sheet.rowCount; i++) {
    if (i % 2 === 0) {
      const row = sheet.getRow(i);
      row.eachCell({ includeEmpty: true }, (cell) => {
        cell.fill = ZEBRA_FILL;
      });
    }
  }
}

function setupSheet(wb: ExcelJS.Workbook, name: string, cols: ColSpec[]): ExcelJS.Worksheet {
  // Excel sheet names are limited to 31 chars; clip safely.
  const sheet = wb.addWorksheet(name.substring(0, 31));
  sheet.columns = cols.map((c) => ({
    header: c.header,
    key: c.key,
    width: c.width || 18,
    style: c.numFmt ? { numFmt: c.numFmt } : undefined,
  }));
  return sheet;
}

export function renderHospitalReportXlsx(report: HospitalReport, output: Writable): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'AbhaAyushman';
  wb.created = new Date();
  wb.lastModifiedBy = report.header.generatedBy.name;

  buildSummarySheet(wb, report);
  buildPatientsSheet(wb, report);
  buildEncountersSheet(wb, report);
  buildDoctorsSheet(wb, report);
  buildDoctorTrendsSheet(wb, report);
  buildAppointmentsSheet(wb, report);
  buildIpdSheet(wb, report);
  buildPharmacySheet(wb, report);
  buildLabSheet(wb, report);
  buildBillingSheet(wb, report);
  buildStaffCollectionsSheet(wb, report);
  buildAbdmSheet(wb, report);

  return wb.xlsx.write(output as any).then(() => undefined);
}

function buildSummarySheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = wb.addWorksheet('Summary');
  sheet.columns = [
    { header: 'Field', key: 'k', width: 36 },
    { header: 'Value', key: 'v', width: 64 },
  ];
  applyHeaderStyle(sheet);

  const h = r.header.hospital;
  const rows: Array<[string, string | number]> = [
    ['Hospital', h?.name || '—'],
    ['Hospital code', h?.code || '—'],
    ['Type', h?.type || '—'],
    ['Address', h ? `${h.address}, ${h.city}, ${h.state} ${h.pincode}` : '—'],
    ['Phone', h?.phone || '—'],
    ['Email', h?.email || '—'],
    ['Website', h?.website || '—'],
    ['HIP ID', h?.hipId || '—'],
    ['HIU ID', h?.hiuId || '—'],
    ['HFR Facility ID', h?.hfrFacilityId || '—'],
    ['ABDM enabled', h?.abdmEnabled ? 'Yes' : 'No'],
    ['', ''],
    ['Reporting window', r.header.range.label],
    ['Range preset', r.header.range.preset],
    ['Range from', r.header.range.from ? r.header.range.from.toISOString() : '—'],
    ['Range to', r.header.range.to ? r.header.range.to.toISOString() : '—'],
    ['Generated at (IST)', r.header.generatedAtIst],
    ['Generated by', `${r.header.generatedBy.name} (${r.header.generatedBy.role})`],
    ['Generated by email', r.header.generatedBy.email],
    ['', ''],
    ['Patients (lifetime)', r.patientKpis.totalLifetime],
    ['Patients (in range)', r.patientKpis.totalInRange],
    ['ABHA-linked (lifetime)', r.patientKpis.abhaLinkedLifetime],
    ['ABHA % (lifetime)', `${r.patientKpis.abhaPercentLifetime}%`],
    ['ABHA-linked (in range)', r.patientKpis.abhaLinkedInRange],
    ['ABHA % (in range)', `${r.patientKpis.abhaPercentInRange}%`],
    ['KYC verified', r.patientKpis.kycVerifiedLifetime],
    ['', ''],
    ['Encounters in range', r.encounters.totalInRange],
    ['Avg encounters/day', r.encounters.avgPerDay],
    ['Doctors (active)', r.doctors.filter((d) => d.isActive).length],
    ['Total doctors', r.doctors.length],
    ['Appointments total', r.appointments.total],
    ['IPD admissions in range', r.ipd.admissionsInRange],
    ['Currently admitted', r.ipd.currentlyAdmitted],
    ['Bed occupancy', `${r.ipd.bedOccupancyPercent}%`],
    ['Total revenue (paid)', r.billing.totalRevenue],
    ['Pharmacy revenue', r.pharmacy.pharmacyRevenue],
    ['Stock value', r.pharmacy.currentStockValue],
    ['Lab tests ordered', r.lab.ordered],
    ['Consents requested', r.abdm.consents.requested],
    ['Consents granted', r.abdm.consents.granted],
    ['Care contexts linked', r.abdm.careContextsLinked],
  ];
  for (const [k, v] of rows) {
    sheet.addRow({ k, v });
  }
}

function buildPatientsSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Patients', [
    { header: 'UHID', key: 'uhid', width: 14 },
    { header: 'First name', key: 'firstName', width: 16 },
    { header: 'Last name', key: 'lastName', width: 16 },
    { header: 'Middle name', key: 'middleName', width: 14 },
    { header: 'Gender', key: 'gender', width: 10 },
    { header: 'DOB', key: 'dob', width: 12 },
    { header: 'Age', key: 'age', width: 8, numFmt: '0' },
    { header: 'Mobile', key: 'mobile', width: 14 },
    { header: 'Email', key: 'email', width: 24 },
    { header: 'ABHA number', key: 'abhaNumber', width: 18 },
    { header: 'ABHA address', key: 'abhaAddress', width: 22 },
    { header: 'KYC status', key: 'kycStatus', width: 12 },
    { header: 'ABHA linked at', key: 'abhaLinkedAt', width: 22 },
    { header: 'City', key: 'city', width: 16 },
    { header: 'State', key: 'state', width: 14 },
    { header: 'Registered at', key: 'registeredAt', width: 22 },
    { header: 'Source', key: 'registrationSource', width: 14 },
    { header: 'Visits in range', key: 'visitsInRange', width: 14, numFmt: '0' },
    { header: 'Last visit', key: 'lastVisitAt', width: 22 },
    { header: 'Lifetime spend (INR)', key: 'lifetimeSpend', width: 18, numFmt: '#,##0.00' },
  ]);
  applyHeaderStyle(sheet);
  for (const p of r.patientRoster) sheet.addRow(p);
  applyZebra(sheet);
}

function buildEncountersSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Encounters', [
    { header: 'Section', key: 'section', width: 18 },
    { header: 'Bucket', key: 'bucket', width: 22 },
    { header: 'Count', key: 'count', width: 14, numFmt: '0' },
  ]);
  applyHeaderStyle(sheet);
  sheet.addRow({ section: 'TOTAL', bucket: 'Encounters in range', count: r.encounters.totalInRange });
  sheet.addRow({ section: 'TOTAL', bucket: 'Average per day', count: r.encounters.avgPerDay });
  sheet.addRow({});
  for (const t of r.encounters.byType) sheet.addRow({ section: 'BY TYPE', bucket: t.type, count: t.count });
  sheet.addRow({});
  for (const s of r.encounters.byStatus) sheet.addRow({ section: 'BY STATUS', bucket: s.status, count: s.count });
  sheet.addRow({});
  for (const d of r.encounters.dailyTrend) {
    sheet.addRow({ section: 'DAILY', bucket: `${d.label} ${d.date.substring(0, 10)}`, count: d.count });
  }
  applyZebra(sheet);
}

function buildDoctorsSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Doctors', [
    { header: 'Doctor', key: 'name', width: 26 },
    { header: 'Specialization', key: 'specialization', width: 18 },
    { header: 'Department', key: 'department', width: 18 },
    { header: 'HPR ID', key: 'hprId', width: 18 },
    { header: 'Reg. no.', key: 'registrationNo', width: 16 },
    { header: 'Active', key: 'isActive', width: 8 },
    { header: 'Unique patients', key: 'uniquePatients', width: 14, numFmt: '0' },
    { header: 'Encounters', key: 'encounters', width: 12, numFmt: '0' },
    { header: 'OPD', key: 'opd', width: 8, numFmt: '0' },
    { header: 'IPD', key: 'ipd', width: 8, numFmt: '0' },
    { header: 'Emergency', key: 'emergency', width: 10, numFmt: '0' },
    { header: 'Tele.', key: 'teleconsult', width: 8, numFmt: '0' },
    { header: 'Follow-ups', key: 'followUps', width: 12, numFmt: '0' },
    { header: 'Days worked', key: 'daysWorked', width: 12, numFmt: '0' },
    { header: 'Avg/day', key: 'avgPatientsPerDay', width: 10, numFmt: '0.0' },
    { header: 'Cancelled', key: 'appointmentsCancelled', width: 12, numFmt: '0' },
    { header: 'No-show', key: 'appointmentsNoShow', width: 10, numFmt: '0' },
    { header: 'Revenue (INR)', key: 'revenueAttributed', width: 16, numFmt: '#,##0.00' },
  ]);
  applyHeaderStyle(sheet);
  for (const d of r.doctors) {
    sheet.addRow({
      name: d.name,
      specialization: d.specialization,
      department: d.department || '—',
      hprId: d.hprId || '—',
      registrationNo: d.registrationNo,
      isActive: d.isActive ? 'Yes' : 'No',
      uniquePatients: d.uniquePatients,
      encounters: d.encounters,
      opd: d.opd,
      ipd: d.ipd,
      emergency: d.emergency,
      teleconsult: d.teleconsult,
      followUps: d.followUps,
      daysWorked: d.daysWorked,
      avgPatientsPerDay: d.avgPatientsPerDay,
      appointmentsCancelled: d.appointmentsCancelled,
      appointmentsNoShow: d.appointmentsNoShow,
      revenueAttributed: d.revenueAttributed,
    });
  }
  applyZebra(sheet);
}

function buildDoctorTrendsSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Doctor Trends', [
    { header: 'Doctor', key: 'name', width: 26 },
    { header: 'Cadence', key: 'cadence', width: 12 },
    { header: 'Bucket', key: 'bucket', width: 22 },
    { header: 'Patients', key: 'count', width: 12, numFmt: '0' },
  ]);
  applyHeaderStyle(sheet);
  for (const d of r.doctors) {
    for (const x of d.trends.daily) {
      sheet.addRow({ name: d.name, cadence: 'Daily', bucket: `${x.label} ${x.date.substring(0, 10)}`, count: x.count });
    }
    for (const x of d.trends.weekly) {
      sheet.addRow({ name: d.name, cadence: 'Weekly', bucket: `Week of ${x.weekStart}`, count: x.count });
    }
    for (const x of d.trends.monthly) {
      sheet.addRow({ name: d.name, cadence: 'Monthly', bucket: x.month, count: x.count });
    }
    for (const x of d.trends.yearly) {
      sheet.addRow({ name: d.name, cadence: 'Yearly', bucket: x.year, count: x.count });
    }
  }
  applyZebra(sheet);
}

function buildAppointmentsSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Appointments', [
    { header: 'Doctor', key: 'name', width: 26 },
    { header: 'Total', key: 'total', width: 10, numFmt: '0' },
    { header: 'Completed', key: 'completed', width: 12, numFmt: '0' },
    { header: 'Cancelled', key: 'cancelled', width: 12, numFmt: '0' },
    { header: 'No-show', key: 'noShow', width: 10, numFmt: '0' },
  ]);
  applyHeaderStyle(sheet);

  sheet.addRow({
    name: 'TOTAL',
    total: r.appointments.total,
    completed: r.appointments.completed,
    cancelled: r.appointments.cancelled,
    noShow: r.appointments.noShow,
  });
  for (const d of r.appointments.byDoctor) {
    sheet.addRow({
      name: d.name,
      total: d.total,
      completed: d.completed,
      cancelled: d.cancelled,
      noShow: d.noShow,
    });
  }
  applyZebra(sheet);
}

function buildIpdSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Admissions', [
    { header: 'Section', key: 'section', width: 16 },
    { header: 'Ward / metric', key: 'ward', width: 26 },
    { header: 'Type', key: 'type', width: 14 },
    { header: 'Admissions', key: 'admissions', width: 14, numFmt: '0' },
    { header: 'Revenue (INR)', key: 'revenue', width: 16, numFmt: '#,##0.00' },
  ]);
  applyHeaderStyle(sheet);
  sheet.addRow({ section: 'TOTAL', ward: 'Admissions in range', admissions: r.ipd.admissionsInRange });
  sheet.addRow({ section: 'TOTAL', ward: 'Currently admitted', admissions: r.ipd.currentlyAdmitted });
  sheet.addRow({ section: 'TOTAL', ward: 'Discharges', admissions: r.ipd.discharges });
  sheet.addRow({ section: 'TOTAL', ward: 'Avg length of stay (days)', admissions: r.ipd.avgLengthOfStay });
  sheet.addRow({ section: 'TOTAL', ward: 'Bed occupancy %', admissions: r.ipd.bedOccupancyPercent });
  sheet.addRow({ section: 'TOTAL', ward: 'Total IPD revenue', revenue: r.ipd.totalIpdRevenue });
  sheet.addRow({});
  for (const w of r.ipd.byWard) {
    sheet.addRow({
      section: 'BY WARD',
      ward: w.ward,
      type: w.type,
      admissions: w.admissions,
      revenue: w.revenue,
    });
  }
  applyZebra(sheet);
}

function buildPharmacySheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Pharmacy', [
    { header: 'Section', key: 'section', width: 18 },
    { header: 'Item / metric', key: 'name', width: 30 },
    { header: 'Qty', key: 'qty', width: 12, numFmt: '0' },
    { header: 'Revenue (INR)', key: 'revenue', width: 16, numFmt: '#,##0.00' },
  ]);
  applyHeaderStyle(sheet);
  sheet.addRow({ section: 'TOTAL', name: 'Dispensed quantity', qty: r.pharmacy.dispensedQty });
  sheet.addRow({ section: 'TOTAL', name: 'Pharmacy revenue', revenue: r.pharmacy.pharmacyRevenue });
  sheet.addRow({ section: 'TOTAL', name: 'Current stock value', revenue: r.pharmacy.currentStockValue });
  sheet.addRow({ section: 'TOTAL', name: 'Items below reorder level', qty: r.pharmacy.lowStockCount });
  sheet.addRow({ section: 'TOTAL', name: 'Batches expiring within 90d', qty: r.pharmacy.expiringSoonCount });
  sheet.addRow({});
  for (const m of r.pharmacy.topByQty) {
    sheet.addRow({ section: 'TOP BY QTY', name: m.name, qty: m.qty, revenue: m.revenue });
  }
  sheet.addRow({});
  for (const m of r.pharmacy.topByRevenue) {
    sheet.addRow({ section: 'TOP BY REVENUE', name: m.name, qty: m.qty, revenue: m.revenue });
  }
  applyZebra(sheet);
}

function buildLabSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Lab', [
    { header: 'Section', key: 'section', width: 18 },
    { header: 'Bucket', key: 'bucket', width: 26 },
    { header: 'Count', key: 'count', width: 12, numFmt: '0' },
  ]);
  applyHeaderStyle(sheet);
  sheet.addRow({ section: 'TOTAL', bucket: 'Tests ordered', count: r.lab.ordered });
  sheet.addRow({ section: 'TOTAL', bucket: 'Completed', count: r.lab.completed });
  sheet.addRow({ section: 'TOTAL', bucket: 'Pending', count: r.lab.pending });
  sheet.addRow({ section: 'TOTAL', bucket: 'Avg TAT (hrs)', count: r.lab.avgTatHours });
  sheet.addRow({});
  for (const c of r.lab.byCategory) {
    sheet.addRow({ section: 'BY CATEGORY', bucket: c.category, count: c.count });
  }
  applyZebra(sheet);
}

function buildBillingSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'Billing', [
    { header: 'Section', key: 'section', width: 18 },
    { header: 'Bucket', key: 'bucket', width: 26 },
    { header: 'Count', key: 'count', width: 12, numFmt: '0' },
    { header: 'Amount (INR)', key: 'amount', width: 18, numFmt: '#,##0.00' },
  ]);
  applyHeaderStyle(sheet);
  sheet.addRow({ section: 'TOTAL', bucket: 'Total revenue (paid)', amount: r.billing.totalRevenue });
  sheet.addRow({ section: 'TOTAL', bucket: 'Discounts given', amount: r.billing.discountsGiven });
  sheet.addRow({ section: 'TOTAL', bucket: 'Outstanding pending', amount: r.billing.outstanding.pending });
  sheet.addRow({ section: 'TOTAL', bucket: 'Outstanding partial', amount: r.billing.outstanding.partial });
  sheet.addRow({});
  sheet.addRow({ section: 'BY SOURCE', bucket: 'Consultation', amount: r.billing.bySource.consultation });
  sheet.addRow({ section: 'BY SOURCE', bucket: 'Pharmacy', amount: r.billing.bySource.pharmacy });
  sheet.addRow({ section: 'BY SOURCE', bucket: 'Labs', amount: r.billing.bySource.labs });
  sheet.addRow({ section: 'BY SOURCE', bucket: 'Scans', amount: r.billing.bySource.scans });
  sheet.addRow({ section: 'BY SOURCE', bucket: 'IPD', amount: r.billing.bySource.ipd });
  sheet.addRow({});
  for (const m of r.billing.byMethod) {
    sheet.addRow({ section: 'BY METHOD', bucket: m.method, count: m.count, amount: m.amount });
  }
  sheet.addRow({});
  for (const d of r.billing.dailyTrend) {
    sheet.addRow({
      section: 'DAILY',
      bucket: `${d.label} ${d.date.substring(0, 10)}`,
      amount: d.revenue,
    });
  }
  applyZebra(sheet);
}

function buildStaffCollectionsSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  // One row per staff member who collected anything in the window. The
  // per-method amounts are flattened into wide CASH/UPI/CARD/BANK columns
  // so the analyst can sort/sum without having to pivot a long table.
  const sheet = setupSheet(wb, 'Staff Collections', [
    { header: 'Collector', key: 'name', width: 28 },
    { header: 'Role', key: 'role', width: 16 },
    { header: 'Email', key: 'email', width: 32 },
    { header: 'Receipts', key: 'count', width: 12, numFmt: '0' },
    { header: 'Total INR', key: 'total', width: 16, numFmt: '#,##0.00' },
    { header: 'Cash', key: 'cash', width: 14, numFmt: '#,##0.00' },
    { header: 'UPI', key: 'upi', width: 14, numFmt: '#,##0.00' },
    { header: 'Card', key: 'card', width: 14, numFmt: '#,##0.00' },
    { header: 'Bank', key: 'bank', width: 14, numFmt: '#,##0.00' },
    { header: 'Other', key: 'other', width: 14, numFmt: '#,##0.00' },
    { header: 'First collected', key: 'first', width: 22 },
    { header: 'Last collected', key: 'last', width: 22 },
  ]);
  applyHeaderStyle(sheet);
  for (const s of r.billing.byStaff) {
    const m = (key: string) =>
      s.byMethod.find((b) => b.method === key)?.amount || 0;
    sheet.addRow({
      name: s.name,
      role: s.role || '—',
      email: s.email || '—',
      count: s.paymentCount,
      total: s.total,
      cash: m('CASH'),
      upi: m('UPI'),
      card: m('CARD'),
      bank: m('BANK_TRANSFER'),
      other: s.byMethod
        .filter((x) => !['CASH', 'UPI', 'CARD', 'BANK_TRANSFER'].includes(x.method))
        .reduce((acc, x) => acc + x.amount, 0),
      first: s.firstCollectedAt ? new Date(s.firstCollectedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : '—',
      last: s.lastCollectedAt ? new Date(s.lastCollectedAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : '—',
    });
  }
  applyZebra(sheet);
}

function buildAbdmSheet(wb: ExcelJS.Workbook, r: HospitalReport) {
  const sheet = setupSheet(wb, 'ABDM', [
    { header: 'Metric', key: 'metric', width: 28 },
    { header: 'Count', key: 'count', width: 14, numFmt: '0' },
  ]);
  applyHeaderStyle(sheet);
  const rows = [
    ['Consents requested', r.abdm.consents.requested],
    ['Consents granted', r.abdm.consents.granted],
    ['Consents denied', r.abdm.consents.denied],
    ['Consents revoked', r.abdm.consents.revoked],
    ['Consents expired', r.abdm.consents.expired],
    ['Consents purged', r.abdm.consents.purged],
    ['Care contexts linked', r.abdm.careContextsLinked],
    ['Scan & Share check-ins', r.abdm.scanShareCheckIns],
    ['HIU records received', r.abdm.externalRecordsReceived],
  ] as const;
  for (const [metric, count] of rows) {
    sheet.addRow({ metric, count });
  }
  applyZebra(sheet);
}
