import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import patientRoutes from '../modules/patient/patient.routes';
import doctorRoutes from '../modules/doctor/doctor.routes';
import appointmentRoutes from '../modules/appointment/appointment.routes';
import abhaRoutes from '../modules/abha/abha.routes';
import consentRoutes from '../modules/consent/consent.routes';
import hospitalRoutes from '../modules/hospital/hospital.routes';
import notificationRoutes from './notificationRoutes';
import auditLogRoutes from './auditLogRoutes';
import paymentRoutes from './paymentRoutes';
import encounterRoutes from '../modules/encounter/encounter.routes';
import prescriptionRoutes from './prescriptionRoutes';
import vitalsRoutes from './vitalsRoutes';
import investigationRoutes from './investigationRoutes';
import hipRoutes from '../modules/hip/hip.routes';
import hiuRoutes from '../modules/hiu/hiu.routes';
import ehrRoutes from '../modules/ehr/ehr.routes';
import ipdRoutes from '../modules/ipd/ipd.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/hospitals', hospitalRoutes);
router.use('/patients', patientRoutes);
router.use('/doctors', doctorRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/abha', abhaRoutes);
router.use('/consents', consentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/payments', paymentRoutes);
router.use('/encounters', encounterRoutes);
router.use('/prescriptions', prescriptionRoutes);
router.use('/vitals', vitalsRoutes);
router.use('/investigations', investigationRoutes);
router.use('/hip', hipRoutes);
router.use('/hiu', hiuRoutes);
router.use('/ehr', ehrRoutes);
router.use('/ipd', ipdRoutes);

export default router;
