/**
 * AbhaAyushman ABDM seed script — single-tenant test fixture.
 *
 * Run AFTER `prisma migrate reset` (or against a clean schema).
 *
 *   npm run seed:abdm
 *
 * What gets created
 * ─────────────────
 *   • 1 Super Admin (platform-wide, no hospital scope)
 *       superadmin@abhaayushman.com / Admin@123
 *   • 1 Hospital   "Shivansh Test Facility"
 *       - Real ABDM sandbox HIP/HIU id (IN2910002104)
 *       - Operating hours, default OPD charge, services, specialties
 *   • 1 Facility (HFR-style) tied to all departments
 *   • 3 Departments (General Medicine, Cardiology, Pediatrics)
 *   • 1 Hospital Admin
 *       admin@shivansh-test-facility.com / Admin@123
 *   • 3 Doctors (each with a linked DOCTOR user, working hours, fee)
 *   • 2 Nurses, 2 Receptionists, 1 Lab Tech, 1 Pharmacist
 *   • 4 Wards (General, Private, ICU, Pediatric) with 20 beds total
 *   • 12 Medicines + 1 stock batch each
 *
 * What is NOT created
 * ───────────────────
 *   • Patients — register via the UI (Scan & Share / new patient form).
 *   • Appointments / Encounters / Admissions / Bills — generated by use.
 *   • Consents / care contexts — generated by ABDM flows.
 */

import { PrismaClient, UserRole } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// ── Real ABDM sandbox identifiers (must match backend .env HIP_ID / HIU_ID) ──
const HIP_ID = 'IN2910002104';
const HIU_ID = 'IN2910002104';
const HOSPITAL_DOMAIN = 'shivansh-test-facility.com';
const HOSPITAL_NAME = 'Shivansh Test Facility';
const HOSPITAL_CODE = 'STF001';

const hash = (pwd: string) => bcrypt.hash(pwd, 10);

// ── Standard hospital schedule (Mon–Sat 08:00–22:00, Sun closed) ─────────────
const operatingHours = {
  mon: { start: '08:00', end: '22:00' },
  tue: { start: '08:00', end: '22:00' },
  wed: { start: '08:00', end: '22:00' },
  thu: { start: '08:00', end: '22:00' },
  fri: { start: '08:00', end: '22:00' },
  sat: { start: '08:00', end: '20:00' },
  sun: null,
};

const breakTimes = [{ start: '13:00', end: '14:00', label: 'Lunch' }];

// Doctor working hours (per-doctor override), same schema as hospital.
const doctorWorkingHours = {
  mon: { start: '09:00', end: '17:00' },
  tue: { start: '09:00', end: '17:00' },
  wed: { start: '09:00', end: '17:00' },
  thu: { start: '09:00', end: '17:00' },
  fri: { start: '09:00', end: '17:00' },
  sat: { start: '09:00', end: '13:00' },
  sun: null,
};

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱  AbhaAyushman ABDM seed');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // ── 1. Super Admin (platform-wide) ──────────────────────────────────────
  const superAdmin = await prisma.user.upsert({
    where: { email: 'superadmin@abhaayushman.com' },
    update: {
      password: await hash('Admin@123'),
      role: 'SUPER_ADMIN',
      hospitalId: null,
      isActive: true,
    },
    create: {
      email: 'superadmin@abhaayushman.com',
      username: 'superadmin',
      password: await hash('Admin@123'),
      firstName: 'AbhaAyushman',
      lastName: 'Super Admin',
      phone: '+91-9000000000',
      role: 'SUPER_ADMIN',
      isActive: true,
    },
  });
  console.log('✅ Super Admin:', superAdmin.email);

  // ── 2. Hospital ─────────────────────────────────────────────────────────
  const hospital = await prisma.hospital.upsert({
    where: { code: HOSPITAL_CODE },
    update: {
      hipId: HIP_ID,
      hipName: HOSPITAL_NAME,
      hiuId: HIU_ID,
      hiuName: HOSPITAL_NAME,
      hfrFacilityId: HIP_ID,
      abdmEnabled: true,
      abdmRegisteredAt: new Date(),
      defaultOpdCharge: 500,
      operatingHours,
      breakTimes,
      defaultSlotDuration: 30,
      services: ['OPD', 'IPD', 'Emergency', 'Pharmacy', 'Lab', 'Radiology'],
      specialties: ['General Medicine', 'Cardiology', 'Pediatrics'],
      totalBeds: 20,
      icuBeds: 4,
      emergencyBeds: 0,
      operationTheaters: 1,
      isActive: true,
      isVerified: true,
      onboardingCompleted: true,
    },
    create: {
      name: HOSPITAL_NAME,
      code: HOSPITAL_CODE,
      type: 'MULTI_SPECIALTY',
      email: `info@${HOSPITAL_DOMAIN}`,
      phone: '+91-22-40001234',
      alternatePhone: '+91-22-40001235',
      website: `https://${HOSPITAL_DOMAIN}`,
      addressLine1: '1 Health Avenue',
      addressLine2: 'Medical District',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400001',
      landmark: 'Near City Hospital',
      registrationNumber: 'REG-STF-001',
      establishedYear: 2020,

      // ABDM
      hipId: HIP_ID,
      hipName: HOSPITAL_NAME,
      hiuId: HIU_ID,
      hiuName: HOSPITAL_NAME,
      hfrFacilityId: HIP_ID,
      abdmEnabled: true,
      abdmRegisteredAt: new Date(),

      // Plan
      plan: 'PROFESSIONAL',
      status: 'ACTIVE',
      maxUsers: 50,
      maxDoctors: 30,
      maxPatients: 5000,
      maxStorage: 20480,

      // Defaults
      defaultOpdCharge: 500,
      operatingHours,
      breakTimes,
      defaultSlotDuration: 30,
      timezone: 'Asia/Kolkata',
      currency: 'INR',
      language: 'en',

      // Facility numbers
      services: ['OPD', 'IPD', 'Emergency', 'Pharmacy', 'Lab', 'Radiology'],
      specialties: ['General Medicine', 'Cardiology', 'Pediatrics'],
      totalBeds: 20,
      icuBeds: 4,
      emergencyBeds: 0,
      operationTheaters: 1,

      isActive: true,
      isVerified: true,
      onboardingCompleted: true,
    },
  });
  console.log(`✅ Hospital: ${hospital.name}  (HIP/HIU=${HIP_ID}, code=${HOSPITAL_CODE})`);

  // ── 3. Facility + Departments ───────────────────────────────────────────
  const facility = await prisma.facility.upsert({
    where: { hfrId: HIP_ID },
    update: {
      name: HOSPITAL_NAME,
      type: 'HOSPITAL',
      address: { line1: '1 Health Avenue', city: 'Mumbai', state: 'Maharashtra', pincode: '400001' },
      contact: { phone: '+91-22-40001234', email: `info@${HOSPITAL_DOMAIN}` },
      isActive: true,
    },
    create: {
      hfrId: HIP_ID,
      name: HOSPITAL_NAME,
      type: 'HOSPITAL',
      address: { line1: '1 Health Avenue', city: 'Mumbai', state: 'Maharashtra', pincode: '400001' },
      contact: { phone: '+91-22-40001234', email: `info@${HOSPITAL_DOMAIN}` },
    },
  });

  const departmentSeeds = [
    { name: 'General Medicine', code: 'GM001',  description: 'General Medicine OPD/IPD' },
    { name: 'Cardiology',       code: 'CARD001', description: 'Cardiology — heart and vascular' },
    { name: 'Pediatrics',       code: 'PED001',  description: 'Pediatrics & Neonatal' },
  ];
  const departments: Record<string, { id: string }> = {};
  for (const d of departmentSeeds) {
    const dept = await prisma.department.upsert({
      where: { hospitalId_code: { hospitalId: hospital.id, code: d.code } },
      update: { name: d.name, description: d.description, facilityId: facility.id, isActive: true },
      create: {
        name: d.name,
        code: d.code,
        description: d.description,
        hospitalId: hospital.id,
        facilityId: facility.id,
      },
    });
    departments[d.code] = dept;
    console.log(`✅ Department: ${d.name}  (code=${d.code})`);
  }

  // ── 4. Hospital Admin ───────────────────────────────────────────────────
  const adminEmail = `admin@${HOSPITAL_DOMAIN}`;
  const hospitalAdmin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {
      password: await hash('Admin@123'),
      role: 'ADMIN',
      hospitalId: hospital.id,
      isActive: true,
    },
    create: {
      email: adminEmail,
      username: 'hospitaladmin',
      password: await hash('Admin@123'),
      firstName: 'Hospital',
      lastName: 'Admin',
      phone: '+91-9810000010',
      role: 'ADMIN',
      hospitalId: hospital.id,
      isActive: true,
    },
  });

  // Set primaryAdminId on hospital (idempotent).
  await prisma.hospital.update({
    where: { id: hospital.id },
    data: { primaryAdminId: hospitalAdmin.id },
  }).catch(() => { /* unique constraint may already be set */ });
  console.log(`✅ Hospital Admin: ${hospitalAdmin.email}`);

  // ── 5. Doctors (with linked DOCTOR user accounts) ───────────────────────
  const doctorSeeds = [
    {
      firstName: 'Aarav', lastName: 'Mehta',
      specialization: 'General Medicine',
      qualification: 'MBBS, MD (Internal Medicine)',
      registrationNo: 'MCI-STF-0001', hprId: 'HPR-STF-AARAV-0001',
      mobile: '+91-9810000101',
      email: `dr.aarav@${HOSPITAL_DOMAIN}`,
      username: 'dr.aarav',
      consultationFee: 500,
      departmentCode: 'GM001',
    },
    {
      firstName: 'Isha', lastName: 'Verma',
      specialization: 'Cardiology',
      qualification: 'MBBS, MD, DM (Cardiology)',
      registrationNo: 'MCI-STF-0002', hprId: 'HPR-STF-ISHA-0002',
      mobile: '+91-9810000102',
      email: `dr.isha@${HOSPITAL_DOMAIN}`,
      username: 'dr.isha',
      consultationFee: 1200,
      departmentCode: 'CARD001',
    },
    {
      firstName: 'Rohan', lastName: 'Iyer',
      specialization: 'Pediatrics',
      qualification: 'MBBS, MD (Pediatrics)',
      registrationNo: 'MCI-STF-0003', hprId: 'HPR-STF-ROHAN-0003',
      mobile: '+91-9810000103',
      email: `dr.rohan@${HOSPITAL_DOMAIN}`,
      username: 'dr.rohan',
      consultationFee: 700,
      departmentCode: 'PED001',
    },
  ];

  for (const d of doctorSeeds) {
    const dept = departments[d.departmentCode];
    const docUser = await prisma.user.upsert({
      where: { email: d.email },
      update: {
        password: await hash('Doctor@123'),
        role: 'DOCTOR',
        hospitalId: hospital.id,
        departmentId: dept.id,
        isActive: true,
      },
      create: {
        email: d.email,
        username: d.username,
        password: await hash('Doctor@123'),
        firstName: d.firstName,
        lastName: d.lastName,
        phone: d.mobile,
        role: 'DOCTOR',
        hospitalId: hospital.id,
        departmentId: dept.id,
        isActive: true,
      },
    });

    await prisma.doctor.upsert({
      where: { registrationNo: d.registrationNo },
      update: {
        firstName: d.firstName,
        lastName: d.lastName,
        specialization: d.specialization,
        qualification: d.qualification,
        mobile: d.mobile,
        email: d.email,
        hprId: d.hprId,
        consultationFee: d.consultationFee,
        workingHours: doctorWorkingHours,
        slotDuration: 30,
        maxPatientsPerDay: 30,
        hospitalId: hospital.id,
        departmentId: dept.id,
        userId: docUser.id,
        isActive: true,
      },
      create: {
        firstName: d.firstName,
        lastName: d.lastName,
        specialization: d.specialization,
        qualification: d.qualification,
        registrationNo: d.registrationNo,
        hprId: d.hprId,
        mobile: d.mobile,
        email: d.email,
        consultationFee: d.consultationFee,
        workingHours: doctorWorkingHours,
        slotDuration: 30,
        maxPatientsPerDay: 30,
        hospitalId: hospital.id,
        departmentId: dept.id,
        userId: docUser.id,
      },
    });
    console.log(`✅ Doctor: Dr. ${d.firstName} ${d.lastName}  (${d.specialization}, fee ₹${d.consultationFee})`);
  }

  // ── 6. Nurses, Receptionists, Lab Tech, Pharmacist ──────────────────────
  type StaffSeed = {
    email: string; username: string; firstName: string; lastName: string;
    role: UserRole; password: string; phone: string; departmentCode?: string;
  };
  const staffSeeds: StaffSeed[] = [
    { email: `nurse.priya@${HOSPITAL_DOMAIN}`,    username: 'nurse.priya',   firstName: 'Priya',  lastName: 'Rao',     role: 'NURSE',          password: 'Nurse@123',  phone: '+91-9810000201' },
    { email: `nurse.kavita@${HOSPITAL_DOMAIN}`,   username: 'nurse.kavita',  firstName: 'Kavita', lastName: 'Nair',    role: 'NURSE',          password: 'Nurse@123',  phone: '+91-9810000202' },
    { email: `reception.front@${HOSPITAL_DOMAIN}`,   username: 'reception.front',   firstName: 'Front',   lastName: 'Desk',     role: 'RECEPTIONIST',   password: 'Recep@123',  phone: '+91-9810000301' },
    { email: `reception.evening@${HOSPITAL_DOMAIN}`, username: 'reception.evening', firstName: 'Evening', lastName: 'Reception', role: 'RECEPTIONIST', password: 'Recep@123',  phone: '+91-9810000302' },
    { email: `lab@${HOSPITAL_DOMAIN}`,            username: 'labtech',       firstName: 'Lab',    lastName: 'Technician', role: 'LAB_TECHNICIAN', password: 'Lab@123',    phone: '+91-9810000401' },
    { email: `pharmacist@${HOSPITAL_DOMAIN}`,     username: 'pharmacist',    firstName: 'Pharma', lastName: 'Cist',    role: 'PHARMACIST',     password: 'Pharma@123', phone: '+91-9810000501' },
  ];

  for (const s of staffSeeds) {
    await prisma.user.upsert({
      where: { email: s.email },
      update: {
        password: await hash(s.password),
        role: s.role,
        hospitalId: hospital.id,
        phone: s.phone,
        isActive: true,
      },
      create: {
        email: s.email,
        username: s.username,
        password: await hash(s.password),
        firstName: s.firstName,
        lastName: s.lastName,
        phone: s.phone,
        role: s.role,
        hospitalId: hospital.id,
        isActive: true,
      },
    });
    console.log(`✅ ${s.role.padEnd(14)}  ${s.email}`);
  }

  // ── 7. Wards + Beds ─────────────────────────────────────────────────────
  type WardSeed = {
    name: string;
    type: 'GENERAL' | 'ICU' | 'PRIVATE' | 'SEMI_PRIVATE' | 'NICU' | 'HDU';
    floor: string;
    dailyCharges: number;
    beds: number;
    bedPrefix: string;
    bedType?: 'STANDARD' | 'ICU' | 'ELECTRIC' | 'PEDIATRIC' | 'BARIATRIC' | 'ISOLATION' | 'BIRTHING';
    hasOxygen?: boolean;
    hasVentilator?: boolean;
    hasMonitor?: boolean;
    hasSuction?: boolean;
  };
  const wardSeeds: WardSeed[] = [
    { name: 'General Ward',   type: 'GENERAL', floor: '1', dailyCharges: 1500, beds: 8, bedPrefix: 'GW',  hasOxygen: true },
    { name: 'Private Ward',   type: 'PRIVATE', floor: '3', dailyCharges: 3000, beds: 4, bedPrefix: 'PVT', hasOxygen: true, hasMonitor: true },
    { name: 'ICU',            type: 'ICU',     floor: '2', dailyCharges: 5000, beds: 4, bedPrefix: 'ICU',
      bedType: 'ICU',  hasOxygen: true, hasVentilator: true, hasMonitor: true, hasSuction: true },
    { name: 'Pediatric Ward', type: 'GENERAL', floor: '4', dailyCharges: 2000, beds: 4, bedPrefix: 'PED',
      bedType: 'PEDIATRIC', hasOxygen: true, hasMonitor: true },
  ];

  for (const w of wardSeeds) {
    let ward = await prisma.ward.findFirst({ where: { hospitalId: hospital.id, name: w.name } });
    if (!ward) {
      ward = await prisma.ward.create({
        data: {
          name: w.name,
          type: w.type as any,
          floor: w.floor,
          dailyCharges: w.dailyCharges,
          totalBeds: w.beds,
          hospitalId: hospital.id,
        },
      });
    } else {
      ward = await prisma.ward.update({
        where: { id: ward.id },
        data: {
          type: w.type as any,
          floor: w.floor,
          dailyCharges: w.dailyCharges,
          totalBeds: w.beds,
        },
      });
    }

    for (let i = 1; i <= w.beds; i++) {
      const bedNumber = `${w.bedPrefix}-${String(i).padStart(2, '0')}`;
      await prisma.bed.upsert({
        where: { wardId_bedNumber: { wardId: ward.id, bedNumber } },
        update: {
          bedType: (w.bedType || 'STANDARD') as any,
          hasOxygen: !!w.hasOxygen,
          hasVentilator: !!w.hasVentilator,
          hasMonitor: !!w.hasMonitor,
          hasSuction: !!w.hasSuction,
          status: 'AVAILABLE',
          cleaningStatus: 'CLEAN',
        },
        create: {
          bedNumber,
          wardId: ward.id,
          status: 'AVAILABLE',
          bedType: (w.bedType || 'STANDARD') as any,
          hasOxygen: !!w.hasOxygen,
          hasVentilator: !!w.hasVentilator,
          hasMonitor: !!w.hasMonitor,
          hasSuction: !!w.hasSuction,
        },
      });
    }
    console.log(`✅ Ward: ${w.name.padEnd(15)} ${w.type.padEnd(8)} ${w.beds} beds @ ₹${w.dailyCharges}/day`);
  }

  // ── 8. Pharmacy: Medicines + stock batches ──────────────────────────────
  type MedicineSeed = {
    name: string;
    generic: string;
    brand?: string;
    manufacturer?: string;
    category: 'TABLET' | 'CAPSULE' | 'SYRUP' | 'INJECTION' | 'OINTMENT' | 'DROPS' | 'INHALER' | 'POWDER' | 'SURGICAL' | 'CONSUMABLE' | 'OTHER';
    strength: string;
    unit: string;
    mrp: number; selling: number; cost: number;
    qty: number;
    monthsToExpiry: number;
    schedule?: string;
  };
  const medicineSeeds: MedicineSeed[] = [
    // Common OPD prescription items
    { name: 'Paracetamol 500mg', generic: 'Paracetamol',  brand: 'Crocin',  manufacturer: 'GSK',          category: 'TABLET',  strength: '500mg', unit: 'pcs',    mrp: 2,    selling: 1.8, cost: 1.0, qty: 1000, monthsToExpiry: 24 },
    { name: 'Amoxicillin 500mg',  generic: 'Amoxicillin',  brand: 'Mox',     manufacturer: 'Cipla',        category: 'CAPSULE', strength: '500mg', unit: 'pcs',    mrp: 8,    selling: 7.0, cost: 4.5, qty: 500,  monthsToExpiry: 18, schedule: 'H' },
    { name: 'Azithromycin 500mg', generic: 'Azithromycin', brand: 'Azithral',manufacturer: 'Alembic',      category: 'TABLET',  strength: '500mg', unit: 'pcs',    mrp: 30,   selling: 27,  cost: 18,  qty: 300,  monthsToExpiry: 18, schedule: 'H' },
    { name: 'Pantoprazole 40mg',  generic: 'Pantoprazole', brand: 'Pan',     manufacturer: 'Alkem',        category: 'TABLET',  strength: '40mg',  unit: 'pcs',    mrp: 12,   selling: 10,  cost: 6,   qty: 400,  monthsToExpiry: 24 },
    { name: 'Cetirizine 10mg',    generic: 'Cetirizine',   brand: 'Cetzine', manufacturer: 'Dr. Reddy\'s', category: 'TABLET',  strength: '10mg',  unit: 'pcs',    mrp: 4,    selling: 3.5, cost: 2.0, qty: 600,  monthsToExpiry: 30 },
    { name: 'Metformin 500mg',    generic: 'Metformin',    brand: 'Glycomet',manufacturer: 'USV',          category: 'TABLET',  strength: '500mg', unit: 'pcs',    mrp: 6,    selling: 5,   cost: 3,   qty: 800,  monthsToExpiry: 24 },
    { name: 'Atorvastatin 10mg',  generic: 'Atorvastatin', brand: 'Atorva',  manufacturer: 'Zydus',        category: 'TABLET',  strength: '10mg',  unit: 'pcs',    mrp: 25,   selling: 22,  cost: 14,  qty: 200,  monthsToExpiry: 24 },

    // Pediatric / fluids
    { name: 'ORS Powder',         generic: 'ORS',          brand: 'Electral',manufacturer: 'FDC',          category: 'POWDER',  strength: '21.8g', unit: 'sachet', mrp: 22,   selling: 20,  cost: 12,  qty: 200,  monthsToExpiry: 36 },
    { name: 'Cough Syrup 100ml',  generic: 'Dextromethorphan', brand: 'Benadryl', manufacturer: 'J&J',     category: 'SYRUP',   strength: '15mg/5ml', unit: 'bottle', mrp: 95, selling: 88, cost: 55, qty: 80, monthsToExpiry: 24 },

    // Injectables
    { name: 'Ceftriaxone 1g Inj', generic: 'Ceftriaxone',  brand: 'Monocef', manufacturer: 'Aristo',       category: 'INJECTION', strength: '1g',  unit: 'vial',   mrp: 65,   selling: 60,  cost: 38,  qty: 100,  monthsToExpiry: 18, schedule: 'H' },
    { name: 'Insulin Regular',    generic: 'Insulin',      brand: 'Huminsulin R', manufacturer: 'Lilly',   category: 'INJECTION', strength: '40IU/ml', unit: 'vial', mrp: 165, selling: 150, cost: 95, qty: 50,  monthsToExpiry: 18 },

    // Topical / consumable
    { name: 'Povidone Iodine 100ml', generic: 'Povidone Iodine', brand: 'Betadine', manufacturer: 'Win-Medicare', category: 'OINTMENT', strength: '5%', unit: 'bottle', mrp: 95, selling: 88, cost: 55, qty: 60, monthsToExpiry: 36 },
  ];

  for (const m of medicineSeeds) {
    const expiry = new Date();
    expiry.setMonth(expiry.getMonth() + m.monthsToExpiry);

    const medicine = await prisma.medicine.upsert({
      where: { name_hospitalId: { name: m.name, hospitalId: hospital.id } },
      update: {
        genericName: m.generic,
        brand: m.brand,
        manufacturer: m.manufacturer,
        category: m.category as any,
        strength: m.strength,
        unit: m.unit,
        mrp: m.mrp,
        sellingPrice: m.selling,
        gstPercent: 12,
        reorderLevel: 50,
        schedule: m.schedule,
        isActive: true,
      },
      create: {
        name: m.name,
        genericName: m.generic,
        brand: m.brand,
        manufacturer: m.manufacturer,
        category: m.category as any,
        strength: m.strength,
        unit: m.unit,
        mrp: m.mrp,
        sellingPrice: m.selling,
        gstPercent: 12,
        reorderLevel: 50,
        schedule: m.schedule,
        hospitalId: hospital.id,
      },
    });

    const batchNumber = 'BATCH-2026-001';
    await prisma.inventoryBatch.upsert({
      where: { medicineId_batchNumber_hospitalId: { medicineId: medicine.id, batchNumber, hospitalId: hospital.id } },
      update: {
        expiryDate: expiry,
        quantityReceived: m.qty,
        quantityAvailable: m.qty,
        costPrice: m.cost,
        sellingPrice: m.selling,
        mrp: m.mrp,
      },
      create: {
        medicineId: medicine.id,
        hospitalId: hospital.id,
        batchNumber,
        expiryDate: expiry,
        quantityReceived: m.qty,
        quantityAvailable: m.qty,
        costPrice: m.cost,
        sellingPrice: m.selling,
        mrp: m.mrp,
      },
    });
  }
  console.log(`✅ Pharmacy: ${medicineSeeds.length} medicines, 1 batch each`);

  // ── 9. Sanity counts ────────────────────────────────────────────────────
  const counts = {
    users: await prisma.user.count(),
    doctors: await prisma.doctor.count(),
    departments: await prisma.department.count(),
    wards: await prisma.ward.count(),
    beds: await prisma.bed.count(),
    medicines: await prisma.medicine.count(),
    inventoryBatches: await prisma.inventoryBatch.count(),
    patients: await prisma.patient.count(),
    appointments: await prisma.appointment.count(),
  };

  console.log('\n📊 Database state');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  for (const [k, v] of Object.entries(counts)) {
    console.log(`  ${k.padEnd(20)}  ${v}`);
  }
  if (counts.patients !== 0 || counts.appointments !== 0) {
    console.warn('\n⚠️  Patients / appointments expected to be 0 — register from the UI.');
  }

  // ── Credentials summary ─────────────────────────────────────────────────
  console.log('\n🎉 Seed complete!\n');
  console.log('📋 Login credentials');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  const creds: Array<[string, string, string]> = [
    ['SUPER_ADMIN',    'superadmin@abhaayushman.com',                'Admin@123'],
    ['ADMIN',          `admin@${HOSPITAL_DOMAIN}`,                   'Admin@123'],
    ['DOCTOR',         `dr.aarav@${HOSPITAL_DOMAIN}`,                'Doctor@123'],
    ['DOCTOR',         `dr.isha@${HOSPITAL_DOMAIN}`,                 'Doctor@123'],
    ['DOCTOR',         `dr.rohan@${HOSPITAL_DOMAIN}`,                'Doctor@123'],
    ['NURSE',          `nurse.priya@${HOSPITAL_DOMAIN}`,             'Nurse@123'],
    ['NURSE',          `nurse.kavita@${HOSPITAL_DOMAIN}`,            'Nurse@123'],
    ['RECEPTIONIST',   `reception.front@${HOSPITAL_DOMAIN}`,         'Recep@123'],
    ['RECEPTIONIST',   `reception.evening@${HOSPITAL_DOMAIN}`,       'Recep@123'],
    ['LAB_TECHNICIAN', `lab@${HOSPITAL_DOMAIN}`,                     'Lab@123'],
    ['PHARMACIST',     `pharmacist@${HOSPITAL_DOMAIN}`,              'Pharma@123'],
  ];
  for (const [role, email, pwd] of creds) {
    console.log(`  ${role.padEnd(14)}  ${email.padEnd(46)}  ${pwd}`);
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`  Hospital : ${hospital.name}`);
  console.log(`  Code     : ${HOSPITAL_CODE}`);
  console.log(`  HIP / HIU: ${HIP_ID}`);
  console.log(`  Domain   : ${HOSPITAL_DOMAIN}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('  Patients: 0 — register fresh ones from the UI.');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
